export const URGENCY_COLORS = {
  Alta: 'bg-red-50 text-red-700 border-red-200',
  Media: 'bg-orange-50 text-orange-700 border-orange-200',
  Baja: 'bg-emerald-50 text-emerald-700 border-emerald-200',
  High: 'bg-red-50 text-red-700 border-red-200',
  Medium: 'bg-orange-50 text-orange-700 border-orange-200',
  Low: 'bg-emerald-50 text-emerald-700 border-emerald-200',
};

export const MAX_FILE_SIZE_MB = 15;

export const TRANSLATIONS = {
  es: {
    app_title: "HealthVibe AI",
    tagline: "Sistema de Triaje IA",
    sub_tagline: "Motor Gemini 3 Pro: Listo",
    upload_title: "1. Evidencia Visual",
    upload_box_title: "Subir Escaneos Biométricos",
    upload_box_desc: "Soporta Foto/Video (Max 15MB)",
    audio_title: "2. Registro de Voz (Opcional)",
    record_btn: "Grabar Síntomas",
    stop_btn: "Finalizar Grabación",
    desc_title: "3. Descripción Clínica",
    desc_placeholder: "Describe la sintomatología, cronología y nivel de dolor...",
    analyze_btn: "Iniciar Diagnóstico IA",
    analyzing_title: "Procesando Datos Biométricos...",
    analyzing_desc: "Gemini 3 Pro está correlacionando síntomas con bases de datos médicas globales.",
    error_title: "Error de Sistema",
    retry_btn: "Reiniciar Secuencia",
    doctor_name: "Dr. HealthVibe",
    doctor_role: "Unidad Médica IA",
    doctor_welcome: "Bienvenido al módulo de triaje avanzado. Mis algoritmos están listos para asistirte.",
    doctor_btn_listen: "Iniciar Protocolo de Voz",
    doctor_btn_listening: "Analizando Audio...",
    doctor_click_hint: "Activar interfaz de voz",
    result_title: "Informe Clínico Generado",
    result_subtitle: "Análisis Multimodal Completado",
    patient_summary: "Resumen del Paciente",
    duration: "Duración",
    pain_level: "Nivel de Dolor",
    symptoms: "Síntomas Detectados",
    referral_letter: "Carta de Derivación",
    view_letter: "Ver Carta Médica",
    hide_letter: "Ocultar Carta",
    warning_signs: "Alertas Críticas Detectadas",
    recommendation: "Recomendación Clínica",
    specialist: "Especialista Sugerido",
    reasoning: "Razonamiento Lógico",
    differential: "Diagnóstico Diferencial",
    immediate_care: "Protocolo de Cuidados Inmediatos",
    follow_up: "Preguntas de Seguimiento",
    new_analysis: "Nuevo Análisis",
    disclaimer: "Aviso: Herramienta de demostración. No sustituye el consejo médico profesional.",
    chat_header: "Asistente Médico Neural",
    chat_placeholder: "Consultar sobre el diagnóstico...",
    chat_init: "He analizado tus datos. ¿Tienes dudas sobre el tratamiento sugerido?"
  },
  en: {
    app_title: "HealthVibe AI",
    tagline: "AI Triage System",
    sub_tagline: "Gemini 3 Pro Engine: Ready",
    upload_title: "1. Visual Evidence",
    upload_box_title: "Upload Biometric Scans",
    upload_box_desc: "Supports Photo/Video (Max 15MB)",
    audio_title: "2. Voice Log (Optional)",
    record_btn: "Record Symptoms",
    stop_btn: "End Recording",
    desc_title: "3. Clinical Description",
    desc_placeholder: "Describe symptomatology, timeline, and pain threshold...",
    analyze_btn: "Initiate AI Diagnosis",
    analyzing_title: "Processing Biometric Data...",
    analyzing_desc: "Gemini 3 Pro is correlating symptoms with global medical databases.",
    error_title: "System Error",
    retry_btn: "Reboot Sequence",
    doctor_name: "Dr. HealthVibe",
    doctor_role: "AI Medical Unit",
    doctor_welcome: "Welcome to the advanced triage module. My algorithms are ready to assist you.",
    doctor_btn_listen: "Initialize Voice Protocol",
    doctor_btn_listening: "Analyzing Audio...",
    doctor_click_hint: "Activate voice interface",
    result_title: "Clinical Report Generated",
    result_subtitle: "Multimodal Analysis Complete",
    patient_summary: "Patient Summary",
    duration: "Duration",
    pain_level: "Pain Level",
    symptoms: "Detected Symptoms",
    referral_letter: "Referral Letter",
    view_letter: "View Medical Letter",
    hide_letter: "Hide Letter",
    warning_signs: "Critical Alerts Detected",
    recommendation: "Clinical Recommendation",
    specialist: "Suggested Specialist",
    reasoning: "Logical Reasoning",
    differential: "Differential Diagnosis",
    immediate_care: "Immediate Care Protocol",
    follow_up: "Follow-up Questions",
    new_analysis: "New Analysis",
    disclaimer: "Notice: Demo tool only. Does not replace professional medical advice.",
    chat_header: "Neural Medical Assistant",
    chat_placeholder: "Ask about the diagnosis...",
    chat_init: "I have analyzed your data. Do you have questions about the suggested treatment?"
  }
};